# Site settings
title: Fredy Rincon
email: fredyrincon@hotmail.com
description: >
  Im Senior Android Developer
#baseurl: "/"
url: "https://fredyrincon.github.io"
fixedNav: 'true' # true or false
#theme: blue # green, blue, orange, purple, grey
twitterUsername: 
githubUsername: fredyrincon
linkedinUsername: fredyrincon
dribbbleUsername:
codepenUsername:

# Build settings
permalink: /:year/:month/:title
markdown: kramdown
include: [_pages]
exclude: [_site, CHANGELOG.md, LICENSE, README.md]
sass:
  style: compressed
